### ISSUE TITLE
rosstalk:Transition Keyer doesn't work

### ISSUE THREAD

**Issue by willosof** [bitfocus/companion-module-rosstalk#1]
_From @tvwonder on August 5, 2018 17:34_

**Describe the bug**
Trying to use the rosstalk:Transition Keyer function and it doesn't work. Assigning this feature to a button then pressing the button does nothing. I get a line in the log in Safari that shows a button was pressed but the switcher does not respond.

**To Reproduce**
1. Assign rosstalk:Transition Keyer to a button (doesn't matter which MLE or Keyer I select or whether Auto Transition is Yes or No)
2. Press assigned button (or Test actions in Safari)
3. None of the keyers transition on or off as expected

**Expected behavior**
I expect the keyer to turn on/off, with our without a transition, depending on how I set the button's parameters

**Screenshots**
![companion rosstalk](https://user-images.githubusercontent.com/13799658/43688296-a5dae0a2-98ab-11e8-98f9-1676e1a92d0c.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.12.6
 - Browser: Safari
 - Version: 11.1.2

_Copied from original issue: bitfocus/companion#197_

**Comment by willosof** [comment]
_From @PerRoine on August 5, 2018 17:39_

We have found the 'Transition Keyer' bug will update it shortly

**Comment by willosof** [comment]
_From @tvwonder on August 5, 2018 17:58_

Awesome. Thanks!

Dave

**Comment by willosof** [comment]
_From @PerRoine on August 5, 2018 19:0_

Ok i Think the 'Transition Keyer' should work now, but i'm at home with no carbonite to test on so please test and give feedback watch for next master build at https://builds.bitfocus.io/companion/
but be aware that this is untested code and not suitable for production environments.

**Comment by willosof** [comment]
_From @tvwonder on August 6, 2018 5:32_

Great! I'll check it when I'm back in the office on Tuesday. Is there any
way to run this build without messing up the main build I already have
installed?

Dave

**Comment by willosof** [comment]
Just install the new build. :) should be fine. To be 100% sure, take a backup of the config files in Library/Application Support/companion :)

**Comment by willosof** [comment]
_From @tvwonder on August 6, 2018 20:13_

OK thanks! :)

**Comment by willosof** [comment]
Can I resolve this?

**Comment by tvwonder** [comment]
Sorry for the delay in getting back to you. I got a chance to test this
yesterday in the latest build (I downloaded it yesterday) and it still
doesn't work. Not sure what else to test with this.

Thanks!

Dave

**Comment by jeremyrmck** [comment]
Was there any progress on this? I'd be happy to help with testing.

**Comment by tvwonder** [comment]
Unfortunately, no. I just downloaded the latest update from yesterday and
it still doesn't work. The button just does nothing.

Dave

**Comment by krocheck** [comment]
@tvwonder are you seeing this behavior with an Acuity/Vision switcher or a Carbonite?

**Comment by tvwonder** [comment]
It's a Carbonite.

Dave

**Comment by krocheck** [comment]
What frame version are you running?  The Carbonite spec is supposed to include direct on/off commands in addition to the standard toggle that is common across all of the switchers.  Right now this module only has implemented the direct on/off method, and it appears to follow the spec.

**Comment by tvwonder** [comment]
I'm a little behind - it's still on 11.1. Would a newer version work? I'm
not going to upgrade until after the first of the year but if this will fix
it then it's more incentive to upgrade.

Thanks.

Dave

**Comment by krocheck** [comment]
Its a guess, but yes.  Since the direct on/off control doesn't exist in the Acuity/Vision spec it leads me to believe Ross added it to the Carbonite spec for use cases more specific to the UltraChromeHR and/or Mosaic frames; therefore would only be in the newer software since those are newer frame types.

Would toggle only control work for you or do you need the granularity of controlling on vs. off?

I'll put it on my list to call into Ross and try to get an answer.

**Comment by tvwonder** [comment]
That makes sense. I really only need to be able to toggle them on/off. If I
need to specify on or off I can just do that with a custom control.

Thanks!

Dave
