### ISSUE TITLE
GPI - Fix Unnecessary Padding 

### ISSUE THREAD

**Issue by shaunmw** [bitfocus/companion-module-rosstalk#10]
GPI Numbers <10 have 0 padded which is not required and will not map correctly. These are treated as alphabetical values vs. numerical so 01 != 1 when parsed on the receiving end.

http://help.rossvideo.com/carbonite-device/Topics/Protocol/RossTalk/MDK/RT-MDK-Comm.html#topic.rt-mdk-comm

https://github.com/bitfocus/companion-module-rosstalk/blob/71ca56a039e5d295f3af8349f3430bd6c5c965fd/rosstalk.js#L472

Simple Fix:

`cmd = 'GPI ' + gpi; `

**Comment by krocheck** [comment]
@shaunmw while I am a user of no Ross products currently, I will note that the Rosstalk documentation for Acuity shows the opposite of what you mention for Carbonite.  I think we all wish it were a 'universal' protocol, but it seems to not be so.  http://help.rossvideo.com/acuity-device/Topics/Protocol/External/VIS/RT-VIS-Comm.html

There is no good processing for product family in the module for the moment.  This will need to be addressed in the future.  But, we need to answer the question of zero padding for Carbonite vs Acuity for this command in the short term.  Maybe Acuity is incorrectly documented (or doesn't care).

**Comment by shaunmw** [comment]
I hadn't noticed that difference. I'll check-in with Ross and get back with
the answer.

**Comment by shaunmw** [comment]
Ross investigated this and leading zero is not an issue on current devices.
