### ISSUE TITLE
Feature Request: Custom labels for Carbonite Custom Controls

### ISSUE THREAD

**Issue by chrisrouse** [bitfocus/companion-module-rosstalk#11]
I’m using multiple custom controls on the tennis event I’m on to trigger a number of actions simultaneously. It would be great if I could label the controls in Companion so that I can know which one is what inside the button.

**Comment by josephdadams** [comment]
I did a test sending `CC?` `CC ?` `CC ?:` `CC ?:` etc. and never got a response.

You probably could get this data using their undocumented bidi protocol that Dashboard uses to pull data into params, pull that into a Dashboard panel, and send it over to Companion that way... but that would not be rosstalk at that point.
