### ISSUE TITLE
Ross Ultrix GPI Triggers

### ISSUE THREAD

**Issue by CoBot3000** [bitfocus/companion-module-rosstalk#13]
**Describe the feature**
I would like to trigger a Ultrix Salvo directly using a GPI directly instead of using a Custom Control from the Carbonite. 
Currently I am having to make a device on the Carbonite and then triggering the Ultrix Salvo from the Carbonite Custom Control. 

I don't know if it is a port issue? as it says in the document attached on page 55 that RossTalk is on TCP: 7788. Other thought could be that the information being sent to the GPI is incorrect? 

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**

![image](https://user-images.githubusercontent.com/53888044/62741334-9afe7300-ba8e-11e9-8018-a6e0ad923712.png)

[Ultrix User Guide (2101DR-004).pdf](https://github.com/bitfocus/companion/files/3483911/Ultrix.User.Guide.2101DR-004.pdf)

**Usecases**
I would like to change the Feed being sent to our reference monitors using the stream deck.

I would like to trigger the Ultix GPI to trigger the Salvo.

**Comment by josephdadams** [comment]
Moving this to the RossTalk module for tracking.

**Comment by ZachIsaiah** [comment]
@CoBot3000 Yo! Were you able to figure it out? If not, I am trying to figure out how to implement your initial setup. Any help would be greatly appreciated.

**Comment by CoBot3000** [comment]
@ZachIsaiah sorry, I just ended up using the Carbonite to control the Confidence Monitors instead. Haven't really looked more into controlling the Ultrix via Companion yet. May look into it again later. We had spare inputs and outputs on the Carbonite so wasn't a pain point at this stage. 

But, by what I can see in the latest version of Companion is that they have added 'Generic SW-P-08 Ross Router' which should give you the control you need to talk to the Ultrix Router.
