### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by brad-c7** [bitfocus/companion-module-rosstalk#16]
At my church we utilize companion to communicate via RossTalk to our video switcher to trigger Custom Controls. 

Something that would be ideal and extremely helpful, is being able to enable instance feedback on these macros...
I'm not sure if there is something that could be programmed on the companion side of things or if this has to go through Ross, but I would like to see it happen as it would be so helpful. Almost like a tally system for the stream deck to show what is live....

Or even deeper thought, something to show what is in preview (green highlight) and what is on program (red highlight)

**Comment by josephdadams** [comment]
@brad-c7 I do this on my Ross Carbonite switcher at my church using the Tally Arbiter Companion module. Works great.
