### ISSUE TITLE
Cue Command left out of Switch Statement

### ISSUE THREAD

**Issue by luthere** [bitfocus/companion-module-rosstalk#17]
Was just wondering if you could add the rosstalk command CUE to the Switch statement. You guys defined it, but never added it.

**Comment by krocheck** [comment]
Well how about that!  I'll add it to my list.  FYI, Xpression functionality in this module is considered deprecated, as there is a [dedicated Xpression module](https://github.com/bitfocus/companion-module-rossvideo-xpression) now and I show the CUE command is setup correctly there.

**Comment by luthere** [comment]
Understood. I will follow that module as well. Thank you.
