### ISSUE TITLE
Feedback using UMD?

### ISSUE THREAD

**Issue by tmdarlan** [bitfocus/companion-module-rosstalk#18]
It would be super useful if the module could provide feedback of the tally state. I suggest that perhaps it could tap into the UMD feed the carbonite is capable of putting out. There may be a better way to do this but this is currently how i do external tally.

**Comment by Caleb-Wishart** [comment]
@josephdadams I know you have done something with UMD before with [ProTally](https://github.com/josephdadams/ProTally).

Is this something relatively easy?

**Comment by josephdadams** [comment]
They send out tally via the TSL 3.1 protocol. Not rosstalk. And it can be UDP or TCP.

There is a UMD Listener module that does this already.

**Comment by josephdadams** [comment]
https://github.com/bitfocus/companion-module-tslproducts-umdlistener

**Comment by Caleb-Wishart** [comment]
Cool, lots of old issues here
