### ISSUE TITLE
Rosstalk for Ultrix Routers

### ISSUE THREAD

**Issue by JohannsLitz** [bitfocus/companion-module-rosstalk#19]
I'm thinking about how to make a stream deck be a suitable substitution for a button panel like the NK using rosstalk and salvos. There's already a rosstalk preset for ross carbonite. Would it be possible to get Rosstalk for utrix on companion?

**Comment by griffon56** [comment]
hi, I was able to control crosspoint on ultrix using SWP-08 - do you confirm salvos cannot be steering using this module ? Is there an other way ?

**Comment by daniep01** [comment]
Salvos are not directly supported in the companion swp-08 module but you can build one by putting multiple crosspoint commands in a button.

**Comment by ZachIsaiah** [comment]
Hi @daniep01, I am very interested in learning how to build a salvo utilizing the crosspoints. Could you explain how you set it up?

**Comment by daniep01** [comment]
I would use the SWP-08 module and add multiple crosspoint actions to a button.

![image](https://user-images.githubusercontent.com/17852298/184316806-c13d5d27-167d-45ce-af24-abae0c415a83.png)

**Comment by lego08201** [comment]
> Ultrix routers can use the SWP-08 protocol which I wrote a Companion module for. Let me know if you need help getting it working.

Hi Danie01,

Ive got my streamdeck working with companion. I wanna know if there is a way to have a feedback light for each souce that is in a certain destination. Just like the ATEM Module there is a feedback dropdown that says  

videohub: Change background color by destination
If the input specified is in use by the output specified, change background color of the bank

I just need this for the Ultrix.

Let me know what you think. 
Thanks!
Ben

**Comment by josephdadams** [comment]
Closing as feedbacks within the rosstalk module are not possible at this time because rosstalk is primarily a one-way protocol. Feel free to open a request on the generic-swp08 module if needed.
