### ISSUE TITLE
Acuity Support

### ISSUE THREAD

**Issue by ecastagne** [bitfocus/companion-module-rosstalk#6]
https://github.com/bitfocus/companion-module-rosstalk/blob/f32c2ad4734c6f220badbd2024bf922e7c1f39dc/rosstalk.js#L597

If line 597 is changed to:
`self.socket.send(cmd + "\r\n");`

This module will be compatible with Acuity switchers, which requires a carriage return in addition to line feed. Unsure if this breaks other switcher support.

**Comment by JeffreyDavidsz** [comment]
We can do a model select in the config. Did you test this line with the switcher?

**Comment by krocheck** [comment]
I'd rather find out if Carbonite and Xpression also support CRLF before going that route.

**Comment by JeffreyDavidsz** [comment]
+1 need to test it first before change

**Comment by ecastagne** [comment]
Agree, tested and working on Acuity version 4.0i build 0241.

**Comment by krocheck** [comment]
I feel like I called and spoke to Ross about this and they said everything is CRLF ... even if certain gear responds to just CR.

**Comment by respectTheCode** [comment]
It looks like CRLF is required everywhere and can confirm that ultrix is not working currently. I have access to carbonite, acuity and ultrix and can test changes.

http://help.rossvideo.com/carbonite-device/Topics/Protocol/RossTalk/CNT/RT-CNT-Comm.html#topic.RT-CNT

**Comment by mrdouglasfish** [comment]
I have an acuity I can test with. I need to figure how to make that change manually and make it carry over

**Comment by JeffreyDavidsz** [comment]
I've updated the module (on my phone) if I remember I'll include it in the core to test

**Comment by respectTheCode** [comment]
Let us know when there is a build that we can test. I can test this afternoon or over the weekend.

**Comment by JeffreyDavidsz** [comment]
Module: Upgraded rossvideo-rosstalk - v1.2.7 - convert all commands to CRLF
