### ISSUE TITLE
RossTalk

### ISSUE THREAD

**Issue by OnlyInternetThings** [bitfocus/companion-module-rosstalk#7]
I'm new to Companion, but I seem to be having trouble to get the RossTalk key transitions to work. All the other commands for XPT and cut, auto trans, etc seam to work. But when i try to turn on and off a key for the Key transitions it doesn't do anything.
Is there an area where you can input custom commands?

Thanks

**Comment by haakonnessjoen** [comment]
Seems to be tested OK
